
#note kill yourself
print("hello world")

print('Hello world')



# want to print multiple lines with one print function
#we have to use triple double quotation or triple single quotation 


print ('''hello
this is example of multiple lines 
for print function''')



# control+/ adds a comment to all lines
# kill 
# yo
# self
# retard




#Use single quotation or double quotation depending on the content of whats printed


print("I'd like to watch a movie")

#I'm fond of the saying "something"
#when we define the text above in python text
#we should let python know which quotations it should not consider
#as a python code 
#way to tell python it is in the text is using \ backslash
print(" I'm fond of the saying \"something\" ")
#How do I define the sentence in a single quotated text? 
print(' I\'m fond of the saying "something" ')


